config/routes.rb
Rails.application.routes.draw do
  resources :concerts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create, :new, :edit]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :concert
  validates :comment, presence: true
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  validates :artist, presence: true
  validates :venue, presence: true
  validates :city, presence: true
  validates :date, presence: true
  validates :description, presence: true
  validates :price, presence: true

  def self.today_concerts
    from = DateTime.now.beginning_of_day
    to =DateTime.now.end_of_day
    
    where(date: from..to) 
  end

  def self.actual_month_concerts
    from = DateTime.now.end_of_day
    to =DateTime.now.end_of_month
    where(date: from..to) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @concert = Concert.find params[:concert_id]
    @concert_comments = @concert.comments
    @comment = @concert.comments.new(comment_params)
    if @comment.save
      redirect_to concert_path(id: params[:concert_id])
    else
      flash[:alert] = "There are some errors with your comment"
      redirect_to concert_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :comment, :date)
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

  def index
    @today_concerts = Concert.today_concerts
    @actual_month_concerts = Concert.actual_month_concerts
  end

  def new
    @concert = Concert.new
  end

  def show
    @concert = Concert.find params[:id]
  end

  def create
    @concert = Concert.new concert_params

    if@concert.save
      flash[:notice] = "Entry created successfully"
      redirect_to concerts_path
    else
      flash[:alert] = "Something went wrong. Let's repeat the entry"
      render 'new'
    end
  end

  def edit
    @concert = Concert.find params[:id]
  end

  def update
    @concert = Concert.find params[:id]

    if @concert.update_attributes concert_params
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    concert = Concert.find params[:id]
    concert.destroy

    redirect_to action: 'index'
  end

  private 

  def concert_params
    params.require(:concert).permit(:artist, :venue, :city, :date, :price, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_create_comments.html.erb
<h3>Comments</h3>
<p><%= comment.name %>: <%= comment.comment %></p>
<% end %>

<h2>Add your comments</h2>
<%= form_for [@concert, @comment] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :comment %>
  <%= f.text_field :comment %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/concerts/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.15/css/bulma.min.css">
  <title>Ironhack(@ironhack) | Twitter</title>
</head>
<body>
<% if flash[:alert] %>
  <%= flash[:alert] %>
<% elsif flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<% if @concert.errors.any? %>
  <ul>
    <% @concert.errors.full_messages.each do |error|%>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for [@concert] do |f| %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <br>
  <%= f.label :venue %>
  <%= f.text_field :venue %>
  <br>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.submit 'Save' %>
<% end %>

</body>

app/views/concerts/edit.html.erb
<h1>Editing the concert <%= @concert.artist %></h1>

<%= render 'form' %>

app/views/concerts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.0.15/css/bulma.min.css">
  <title>Ironhack(@ironhack) | Twitter</title>
</head>
<body>
  <div>
    <div class="today_concerts">
      <h1>Today Concerts</h1>
        <ul>
          <% @today_concerts.each do |entry| %>
            <li>
              <h2><%= link_to(entry.artist, concert_path(entry.id)) %></h2>
              Venue: <%= entry.venue %>
              City: <%= entry.city %>m
              Date: <%= entry.date.to_date %>
              Price: <%= entry.price %>
              Description: <%= entry.description %>
            </li>
            <%end%>
        </ul>
    </div>
    <div class="next_month_concerts">
      <h1>Next month Concerts</h1>
        <ul>
          <% @actual_month_concerts.each do |entry| %>
            <li>
              <h2><%= link_to(entry.artist, concert_path(entry.id)) %></h2>
              Venue: <%= entry.venue %>
              City: <%= entry.city %>m
              Date: <%= entry.date.to_date %>
              Price: <%= entry.price %>
              Description: <%= entry.description %>
            </li>
            <%end%>
        </ul>
    </div>
  </div>
</body>
</html>

app/views/concerts/new.html.erb
<h1>Please create a concert</h1>

<%= render 'form' %>

app/views/concerts/show.html.erb
  <div>
    <div class="concert_details">
      <h1>Concert details</h1>
        <ul>
            <li>
              <h2><%= @concert.artist %></h2>
              Venue: <%= @concert.venue %>
              City: <%= @concert.city %>m
              Date: <%= @concert.date.to_date %>
              Price: <%= @concert.price %>
              Description: <%= @concert.description %>
              <%= link_to 'Edit', edit_concert_path(@concert.id) %>
              <%= link_to('Delete', concert_path(@concert.id), method: :delete,data:{confirm: 'Are you sure?'}) %>
            </li>
        </ul>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertNetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h2>Concert Network</h2>
</header>
<%= yield %>
  <footer class="footer">
    <h3>Ironhack - Powered by Ru</h3>
  </footer>

</body>
</html>